### PR TITLE
Optionally rename non-web test directory

### PR DESCRIPTION
**Pull request by pjo336**
The rename script was missing the folder for `test/myapp/*`, this adds it in similar to how the lib folders are done.

### CODE REVIEW

**Comment by pjo336** [comment]
@nickjj Sorry hope it's okay to tag you! Love this setup

**Comment by nickjj** [comment]
Hi,

Currently there's no `test/hello` directory in the project at https://github.com/nickjj/docker-phoenix-example/tree/main/test. Running a `mv` command will fail because the directory doesn't exist.

**Comment by pjo336** [comment]
Ohh gotcha. I must have run the auth gen on my own. Thanks I'll close!

**Comment by nickjj** [comment]
No problem, yeah this project doesn't run the auth generator.

But I do see how it would be useful to have this get renamed if you added in your own non-web tests later. Maybe this is a spot where we can add the directory with a `.keep` file. Before pulling the trigger on that, I wonder if there's anything that can be added to this project to avoid needing to make the `.keep` file since it feels like something you'd delete once you've created your first test since that directory would never be empty after that.

**Comment by pjo336** [comment]
Could also potentially just do a silent failure on the mv command for that dir. makes it a bit nastier but then supports both situations

**Comment by nickjj** [comment]
Yeah I think that's probably the way to go.

I think we can minify the nastiness (avoiding an if condition and letting us keep the 1 liner) by doing `mv test/"${FIND_APP_NAME}" test/"${APP_NAME}" 2> /dev/null || true`. This will return an exit code of 0 and it won't print that the path doesn't exist. You can test it in a terminal with `mv a b 2> /dev/null || true && echo $?`, it'll echo back 0.

**Comment by pjo336** [comment]
Tried it out with both folder existing and folder missing, seems to work as expected

**Comment by nickjj** [comment]
Thanks, can you rebase / amend things so it's 1 commit with a message of: "Optionally rename non-web test directory"

**Comment by pjo336** [comment]
Hey hey, I will 100% do that. Away from computers for the weekend though

**Comment by pjo336** [comment]
@nickjj donezo!

**Comment by nickjj** [comment]
Thanks a lot, just to keep this commit isolated to only you (without me adding extra commits), can you also update the changelog to account for this change.

In the `## [Unreleased]` section near the top there's a `### Fixed` sub-section.

Can you change that to go from:

```md
### Fixed

- `COPY --chown=node:node ../ ../` has been fixed to be `COPY --chown=node:node . ..`
```

To this:

```md
### Fixed

- `COPY --chown=node:node ../ ../` has been fixed to be `COPY --chown=node:node . ..`
- Ensure the `rename-project` script renames your project after adding custom non-web tests
```

Then amend your commit so it's 1 commit and it'll be good to go to merge. Sorry for not including this earlier.

**Comment by pjo336** [comment]
Think I got it this time 😂

**Comment by nickjj** [comment]
Thanks, we're all set.

**Pull request merged**
