### PR TITLE
Use Elixir 1.13.4 for the prod build stage

### PR DESCRIPTION
**Pull request by j-m-hoffmann**

### CODE REVIEW

**Comment by nickjj** [comment]
Thanks, good catch,

Can you amend your commit message to be: "Use Elixir 1.13.4 for the prod build stage"

**Comment by j-m-hoffmann** [comment]
Done

**Comment by nickjj** [comment]
Sorry I mean for the commit message itself.

You can run:

`git commit --amend` and then put `Use Elixir 1.13.4 for the prod build stage` as the new message and `git push origin fix/use-same-version --force`.

**Comment by j-m-hoffmann** [comment]
Done

**Comment by nickjj** [comment]
Cool, thanks again for the patch!

**Pull request merged**
